Added obligatory user task validation field for assignee, candidate user
Activiti/activiti-cloud-org-service pull request #264
Opened 2019-07-09 15:12 UTC by pancudaniel7

and candidate groups.

2019-07-09 15:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud-org-service?pullRequest=264) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud-org-service?pullRequest=264) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud-org-service?pullRequest=264) it.</sub>

2019-07-10 11:35 UTC, constantin-ciobotaru commented
It looks ok to me.

2019-07-10 11:38 UTC, constantin-ciobotaru reviewed
It looks ok to me.

2019-07-11 14:31 UTC, erdemedeiros requested changes
Some small details.

2019-07-11 14:31 UTC, erdemedeiros commented on activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ProjectControllerIT.java
> +    public void testExportProjectWithNoAssigneeValidationErrors() throws Exception {
Could you rename the test to something like `exportProjectWithNoAssigneeShouldReturnErrors`?

2019-07-11 14:31 UTC, erdemedeiros commented on activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/validation/ProcessModelValidator.java
> +    public final String NO_ASSIGNEE_DESCRIPTION = "One of the attributes 'assignee','candidate user' or 'candidate groups' are mandatory on user task";
Here, I think we should use names as they are in the XML file. I mean `candidateUsers`, `candidateGroups` instead of `candidate user`, `candidate groups`.

2019-07-11 15:00 UTC, pancudaniel7 commented on activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ProjectControllerIT.java
> +    public void testExportProjectWithNoAssigneeValidationErrors() throws Exception {
Should I remove also test prefix for the rest of the class methods ?

2019-07-15 11:07 UTC, erdemedeiros commented on activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ProjectControllerIT.java
> +    public void testExportProjectWithNoAssigneeValidationErrors() throws Exception {
This one is enough in the scope of this PR, thanks.

2019-07-15 11:08 UTC, erdemedeiros approved these changes

2019-07-15 11:22 UTC, merged

2019-07-15 14:54 UTC, erdemedeiros commented
Ref https://github.com/Activiti/Activiti/issues/2828.