[AAE-286] first implementation to secure end points for projects and models
Activiti/activiti-cloud-org-service pull request #445
Opened 2019-11-27 21:04 UTC by CTI777

First attempts to secure end points, so that only creator can see processes and models

2019-12-16 20:01 UTC, magemello commented
I think would be a much cleaner solution implement filters....example:

```
@WebFilter(urlPatterns = "/v1/projects/*")
public class ProjectPermissionFilter implements Filter {

    @Autowired
    private ProjectService projectService;

    @Override
    public void doFilter(ServletRequest servletRequest,
                         ServletResponse servletResponse,
                         FilterChain filterChain) throws IOException, ServletException {

        boolean permission = hasPersission(servletRequest);
        if (permission) {
            filterChain.doFilter(servletRequest,
                                 servletResponse);
        }else{
          returnInterruptingResponse(servletResponse,
                                          HttpStatus.FORBIDDEN);
                return;
       }
    }

    private void returnInterruptingResponse(ServletResponse servletResponse,
                                           HttpStatus forbidden) {
        HttpServletResponse resp = (HttpServletResponse) servletResponse;
        resp.reset();
        resp.setStatus(forbidden.value());
    }

    @Override
    public void destroy() {

    }
}

```

2019-12-16 20:03 UTC, magemello requested changes

2019-12-16 20:03 UTC, magemello commented on activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/controller/ProjectController.java
> +    private Project findProjectWithCheckRights(String projectId) {
please implement filters as from my comment

2019-12-16 22:57 UTC, magemello commented on activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/controller/ProjectController.java
> +    private Project findProjectWithCheckRights(String projectId) {
can you add also test to the PR?

2019-12-18 21:35 UTC, CTI777 commented
Test changes applied here are not valid, the whole new logic will be implemented in the modeling-service

2019-12-18 21:35 UTC, closed without merging